### ISSUE TITLE
The `isNumber` value guard uses `+` to convert a string to a number

### ISSUE THREAD

**Issue by deadalusai** [TradeMe/ensure#3]
Since the `isNumber` value guard uses `+` to convert a string to a number, this has the side-effect of treating a whitespace-only or empty string as zero. E.g. `+'   '` resolves to `0`.

This should probably be treated as an error case. Using `parseInt(..., 10)` instead should resolve this.

**Comment by phenomnomnominal** [comment]
Probably gonna go with `parseFloat`?

**Comment by deadalusai** [comment]
Sure, if you really want to support floats..
