### ISSUE TITLE
Support custom "getter" value guards

### ISSUE THREAD

**Issue by deadalusai** [TradeMe/ensure#4]
`isNotNull` is currently special-cased to only run on get. Can we support marking custom value guard functions to run on get?

An attribute would be petty cool, e.g.

```
import { Guard } from '@trademe/ensure';

@Guard({ onGet: true })
function myGuard () {
   ...
}
```

**Comment by phenomnomnominal** [comment]
TIL you can’t do a @Decorator on a function...
